Repository zincware/IPSuite, pull requests merged in 2024-04, with the labels that each got.

#264 Docs
  .readthedocs.yaml
  README.md
  docs/Makefile
  docs/make.bat
  docs/source/_get_started/ips.rst
  docs/source/_get_started/quickstart.rst
  docs/source/_nodes/ipsuite.analysis.model.rst
  docs/source/_nodes/ipsuite.analysis.rst
  docs/source/_nodes/ipsuite.base.rst
  docs/source/_nodes/ipsuite.bootstrap.rst
  docs/source/_nodes/ipsuite.calculators.rst
  docs/source/_nodes/ipsuite.configuration_comparison.rst
  docs/source/_nodes/ipsuite.configuration_generation.rst
  docs/source/_nodes/ipsuite.configuration_selection.rst
  docs/source/_nodes/ipsuite.data_loading.rst
  docs/source/_nodes/ipsuite.fields.rst
  docs/source/_nodes/ipsuite.geometry.rst
  docs/source/_nodes/ipsuite.models.rst
  docs/source/_nodes/ipsuite.project.rst
  docs/source/_nodes/ipsuite.rst
  docs/source/_nodes/ipsuite.static_data.rst
  docs/source/_nodes/ipsuite.utils.rst
  docs/source/_nodes/modules.rst
  docs/source/conf.py
  docs/source/examples/01_Data_Loading_and_Selection.ipynb
  docs/source/examples/02_Training_Models.ipynb
  docs/source/examples/03_Analysing_Datasets_and_Model_Predictions.ipynb
  docs/source/examples/04_Molecular_Dynamics_Structure_Generation_and_Simulation.ipynb
  docs/source/examples/05_Labeling_with_Calculators.ipynb
  docs/source/examples/06_Bootstrapping_Datasets.ipynb
  docs/source/images/jigsaw_nodes.png
  docs/source/images/mlp.png
  docs/source/images/water_packmol.png
  docs/source/index.rst
  index.rst
  ipsuite/analysis/model/__init__.py
  ipsuite/bootstrap/__init__.py
  ipsuite/calculators/__init__.py
  ipsuite/calculators/ase_geoopt.py
  ipsuite/configuration_generation/packmol.py
  ipsuite/geometry/__init__.py
  ipsuite/models/__init__.py
  ipsuite/utils/__init__.py
  ipsuite/utils/combine.py
  ipsuite/utils/docs.py
  poetry.lock
  pyproject.toml
Labels: documentation

#273 Metrics cleanup
  ipsuite/analysis/__init__.py
  ipsuite/analysis/model/__init__.py
  ipsuite/analysis/model/plots.py
  ipsuite/analysis/model/predict.py
  ipsuite/base/__init__.py
  ipsuite/base/base.py
  ipsuite/bootstrap/surface_mods.py
  ipsuite/nodes.py
  ipsuite/utils/metrics.py
  tests/integration/test_ensemble.py
  tests/integration/test_i_apax.py
  tests/integration/test_i_model_analysis.py
Labels: enhancement, 🎉 new node

#286 updated docstrings
  ipsuite/analysis/bin_property.py
Labels: documentation

#282 Rename modifiers
  ipsuite/analysis/model/dynamics.py
  ipsuite/analysis/model/dynamics_checks.py
  ipsuite/analysis/sensitivity.py
  ipsuite/base/__init__.py
  ipsuite/base/base.py
  ipsuite/calculators/ase_geoopt.py
  ipsuite/calculators/ase_md.py
  tests/integration/calculators/test_ase_md.py
  tests/unit_tests/calculators/test_u_ase_geoopt.py
Labels: enhancement
